# Generated by Django 4.0.3 on 2022-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0002_channelslink_yourprofile_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelslink',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
